### ISSUE TITLE
`echodoc#util#get_func_text()` makes insertion extremely slow

### ISSUE THREAD

**Issue by nfnty** [Shougo/echodoc.vim#22]
Since 0abba0c32f083f2f4bee4976252d3caeb17cbb18 insertion has been extremely slow in large files with dense text.

Is there a more efficient way of implementing multiline function scanning?

**Comment by tweekmonster** [comment]
How large is the file?  Do you have the `timers` feature?  I've been using it just fine in files that are like 12,000 LOC.

**Comment by nfnty** [comment]
Yes, running on latest neovim.
You can replicate the behavior by inserting at EOF of this file: https://gist.github.com/52cf5114a222a6e094e5a8c5fc219a4d

**Comment by tweekmonster** [comment]
Oh okay, I see now.  It never hits a parenthesis.  Maybe `get_func_text()`'s `line_guard` variable should be based on the current filetype.  Try setting `line_guard` to 3 or something conservative and see if that improves it.

Out of curiosity, why are you editing a ctags file?

**Comment by nfnty** [comment]
Setting `line_guard` seems quite hacky for what should be fixed with a better scan function.

It was originally from a huge diff file. I just modified it a bit for replication.

**Comment by tweekmonster** [comment]
> Setting line_guard seems quite hacky for what should be fixed with a better scan function.

Not really.  The line guard is meant to be a high water mark for multiline function calls.  There are cases where it doesn't need to scan that many lines backwards.  I just wanted you to try it to see if actually improved performance.  The plugin could change it based on the file type or how long it takes to do one scan.  Maybe even give up early if doesn't encounter delimiters (e.g. `,()[]{}`) within 2-3 lines.

If you can think of a better way to do the scan let me know.  I wrote it the way it is now because `searchpos()` isn't very reliable for finding open parenthesis and skipping balanced ones.  I thought about doing it in a Python thread but I think it wouldn't help due to the GIL.

Another option is to use the old echodoc method by default and, if available, use an async job to do the parsing in a subprocess.  @Shougo WDYT?

**Comment by Shougo** [comment]
> Another option is to use the old echodoc method by default and, if available, use an async job to do the parsing in a subprocess. @Shougo WDYT?

I think it is better to use subprocess.
